export * from './Auth';
export * from './Content';
export * from './Profile';
export * from './Home';
export * from './Videos';
export * from './[productName]';
export * from './FAQ';
export * from './About';
export * from './Politics';
export * from './NotFound';
export * from './Services'